### PR TITLE
lots of test coverage and some fixes

### PR DESCRIPTION
**Pull request by edwardne**
test coverage is now at 62%

fixed getship() and other some other things

I started a few test for methods at the top of BattleShipModel before I saw Jiayu's e-mail. then went from the bottom up

### CODE REVIEW

**Comment by edwardne** [comment]
Actually it looks like it still might not be setting the mode correctly still, but this is still fixing some of the problems. Getting rid of that AIdh(), AIcl, etc... brought it down to about 57% line coverage(seems to vary a bit on runs).

**Comment by geddingj** [comment]
After accepting the previous pull this one now has some conflicts in it

**Comment by edwardne** [comment]
fixed conflicts

**Comment by geddingj** [comment]
Cool! Sending through now

**Pull request merged**
