### PR TITLE
Code Clean up

### PR DESCRIPTION
**Pull request by jiayuhan94**
I did some code clean up.
ATTENTION
The easy hard mode button is not working properly. It`s always easy mode which is kinda weird. I put break point at both return currmodel for easy and hard mode. It never stopped there.

### CODE REVIEW

**Comment by geddingj** [comment]
If you're running on firefox the script on the buttons will lock -- chrome handles it better. Unless something new is interfering with them.

Regardless, tomorrow I'll patch that part up since it's not necessary for completion.

Don't understand what you're trying to do with the setter function however.

**Comment by jiayuhan94** [comment]
Basically, I mean no matter I choose easy or hard mode. It's always easy
mode. The ezmode didn't change to false as expected for hard mode.

**Comment by jiayuhan94** [comment]
Also,  the setezmode method in main class is suppose to call setmode in
battleshipmodel class. When I was debugging, I set two break points to stop
return to check what's wrong. Since it didnt stop there, I would say
something is wrong there.

**Comment by geddingj** [comment]
Odd, wasn't that way when it was sent through. I'm signing off for the night but will take a look at it in the morning.

**Comment by geddingj** [comment]
Was bugging me so I stayed up a bit longer to print out the lines with the existing code:

-Correct value is being sent through the POST request
-Correct calling of setEzmode function
-Correct setting of boolean value

The ezPlace() and hardplace() I forgot was added, though technically a breach in the 'setter' philosophy it doesn't really matter. I also just searched for a "setmode" function in BattleshipModel and came back with nothing. 

Will just accept your pull request since it's changes work best for you.

**Pull request merged**
